### ISSUE TITLE
Incorrect link in web page https://aldostools.org/ps3/

### ISSUE THREAD

**Issue by kyklish** [aldostools/Resources#14]
# Desctiption
Last line in web page: [https://aldostools.org/ps3/](https://aldostools.org/ps3/) 

Install the [offline pkg](http://ps3.aldostools.org/webportal.pkg) then set [this link](http://localhost/dev_hdd0/game/WEBPORTAL/index.html) as the browser's startup page in Tools > Homepage

# Error
`this link` is wrong `http://localhost/dev_hdd0/game/WEBPORTAL/index.html`, you miss `USRDIR`

# Solution
Correct link: `http://localhost/dev_hdd0/game/WEBPORTAL/USRDIR/index.html`

**Comment by aldostools** [comment]
Thank you for the correction. I just fixed the link in https://aldostools.org/ps3/

BTW this is an alias of https://ps3.aldostools.org/

**Comment by kyklish** [comment]
> Thank you for the correction. I just fixed the link in https://aldostools.org/ps3/
> 
> BTW this is an alias of https://ps3.aldostools.org/

Thanks, but here [https://ps3.aldostools.org/](https://ps3.aldostools.org/) link is not fixed 🫣. Is it two separate (identical) pages and not alias of?

On one link is fixed, on another is not fixed.
